---
name: Awesome DNS pull request
description: GitHub pull request for modification of Awsesome DNS list
title: '[ADD/DELETE/UPDATE]: "Software name"'
labels: ["pr", "triage"]
assignees:
  - mylespat
  - gjherbiet
body:
  - type: dropdown
    id: type
    attributes:
      label: Pull request type
      description: >
        What change best describes the content of the pulll request?
      options:
        - New addition
        - Deletion
        - Update
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        **Please fill at least the name of the software and the
        fields for which you suggest an update.**
  - type: input
    id: name
    attributes:
      label: Software name
      description: Complete name of the software
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Software webpage
      description: URL of the software web page
    validations:
      required: false
  - type: input
    id: description
    attributes:
      label: Software description
      description: Short description of the software
    validations:
      required: false
  - type: input
    id: organization
    attributes:
      label: Editing organization
      description: Organization that edits the software
    validations:
      required: false
  - type: input
    id: license
    attributes:
      label: Software license
      description: License under which the software is licensed
    validations:
      required: false
  - type: input
    id: category-name
    attributes:
      label: Category name
      description: Suggested category for the software
    validations:
      required: false
  - type: checkboxes
    id: category-new
    attributes:
      label: New category
      description: Is the suggested category a new category?
      options:
        - label: Yes, it's a new category
        - label: No, it's an existing category
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Motivate the changes in the pull request
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Request checklist
      description: >
        Check the following boxes to ensure you have completed each step
        before submitting your suggestion
      options:
        - label: I have checked for other similar pull requests and issues
        - label: I have set the correct type in the pull request title
        - label: >
            I have replaced "Software name" by the actual name of the
            software in the title
        - label: I have filled all mandatory fields
    validations:
      required: true
