---
name: Deletion from list
description: Suggest deletion of a software from the list
title: '[REMOVE]: "Software name"'
labels: ["remove", "triage"]
assignees:
  - mylespat
  - gjherbiet
body:
  - type: input
    id: name
    attributes:
      label: Software name
      description: Complete name of the software
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Motivate the deletion of the software from the list
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Request checklist
      description: >
        Check the following boxes to ensure you have completed each step
        before submitting your suggestion
      options:
        - label: I have checked for other similar issues and pull requests.
        - label: >
            I have replaced "Software name" by the actual name of the
            software in the title
        - label: I have filled all mandatory fields
    validations:
      required: true
